name: Deploy to Tarhely.eu
on:
  push:
    branches:
      - master

jobs:
  web-deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
    - name: Get latest code
      uses: actions/checkout@v3

    - name: Deploy to Tarhely.eu
      run: |
        sudo apt-get update
        sudo apt-get install lftp -y
        
        lftp -p 21 -u "${{ secrets.FTP_USERNAME }},${{ secrets.FTP_PASSWORD }}" "${{ secrets.FTP_SERVER }}" <<EOF
        set ftp:ssl-allow no
        set ftp:passive-mode on
        set net:max-retries 2
        set net:timeout 10
        # This will explicitly copy files into the public_html folder
        mirror -R --verbose=3 --no-symlinks ./ public_html/
        quit
        EOF