name: Deploy to Tarhely.eu
on:
  push:
    branches:
      - master

jobs:
  web-deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
    - name: Get latest code
      uses: actions/checkout@v3

    - name: Deploy to Tarhely.eu (Fixed Path)
      run: |
        lftp -p 21 -u "${{ secrets.FTP_USERNAME }},${{ secrets.FTP_PASSWORD }}" "${{ secrets.FTP_SERVER }}" <<EOF
        set ftp:ssl-allow no
        set ftp:passive-mode on
        set net:max-retries 2
        set net:timeout 10
        # A '.' azt jelenti: a jelenlegi mappa, amibe bejelentkeztünk
        mirror -R --verbose=3 --no-symlinks ./ .
        quit
        EOF